apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline

metadata:
  name: nginx-app-delivery-pipeline
  labels:
    app: nginx-app

description: "Multi-stage delivery pipeline for nginx application deployment."

suspended: false

serialPipeline:
  stages:
    - targetId: development
      profiles:
        - dev

    - targetId: staging
      profiles:
        - test

    - targetId: prod
      profiles:
        - prod

---
apiVersion: deploy.cloud.google.com/v1
kind: Target

metadata:
  name: development
  labels:
    app: nginx-app
    env: development
description: "This target will be use for dev environment."

run:
  location: projects/devops-project-495401/locations/us-east1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target

metadata:
  name: staging
  labels:
    app: nginx-app
    env: staging
description: "This target will be use for staging environment."

run:
  location: projects/devops-project-495401/locations/us-east1  

---

apiVersion: deploy.cloud.google.com/v1
kind: Target

metadata:
  name: prod
  labels:
    app: nginx-app
    env: prod
description: "This target will be use for prod environment."

run:
  location: projects/devops-project-495401/locations/us-east1

executionConfigs:
  - usages:
      - RENDER
      - DEPLOY