substitutions:
  _REGION: 'us-east1'
  _REPOSITORY: 'docker-repo'
  _IMAGE: 'nginx-app'
  _LOG_BUCKET: 'devops_ci_logs'

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'apply-and-deploy'
    entrypoint: 'bash'
    args: 
    - '-c'
    - |
        set -e
        # 1. create delivery pipeline

        gcloud deploy apply \
        --file=clouddeploy.yaml \
        --region=${_REGION} \
        --project=$PROJECT_ID

        # 2. create the release to deploy image

        gcloud deploy releases create release-${SHORT_SHA} \
          --delivery-pipeline=nginx-app-cd-pipeline \
          --region=${_REGION} \
          --images=nginx-app=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}

logsBucket: 'gs://${_LOG_BUCKET}'