apiVersion: skaffold/v4beta7
kind: Config

metadata:
  name: nginx-app

manifests:
  rawYaml:
    - service.yaml

deploy:
  cloudrun: {}

profiles:
  - name: prod
    manifests:
      rawYaml:
        - service.yaml
    deploy:
      cloudrun: {}
      